[project]
name = "hashflow"
version = "0.0.1"
authors = [
  { name="Sameer Brenn", email="sameer@hashflow.com" },
]
description = "An implementation of the Hashflow API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = ["requests"]

[project.urls]
"Homepage" = "https://github.com/hashflownetwork/hashflow-py"

[build.system]
requires = ["hatchling"]
build-backend = "hatchling.build"
